GET https://demo.jiniworld.me/test/mili HTTP/1.1

###

POST https://demo.jiniworld.me/token HTTP/1.1
content-type: application/json

{
  "apikey": "lf2McyT3V5gDu2pNNm4VxmX3C2mezX3s",
  "nonce": "1645629314542"
}

###

POST https://demo.jiniworld.me/token HTTP/1.1
content-type: application/json

< ./body.json